### ISSUE TITLE
sdf

### ISSUE THREAD

**Issue by mehrnazayazi** [mehrnazayazi/xv6#1]
lskdjflsdkj

```
version: "3"
services:
    judge_server:
        build: .
        read_only: true
        cap_drop:
            - SETPCAP
            - MKNOD
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
            - FSETID
        tmpfs:
            - /tmp
        volumes:
            - ./tests/test_case:/test_case:ro
            - ./log:/log
            - ./run:/judger
        environment:
            - BACKEND_URL=http://127.0.0.1:8000/api/judge_server_heartbeat
            - SERVICE_URL=http://127.0.0.1:12358
            - TOKEN=03AC674216F3E15C761EE1A5E255F067953623C8B388B4459E13F978D7C846F4
            - judger_debug=1
        ports:
            - "0.0.0.0:12358:8080"


```
